### ISSUE TITLE
Getting Non-base58 character error 

### ISSUE THREAD

**Issue by brishtiteveja** [spknetwork/honeycomb-spkcc#1]
Getting this error  while running in the docker.

----------

honeycomb_1  | Blocks to apply: 2                                                                  
honeycomb_1  | Blocks to apply: 1                                                                  
honeycomb_1  | Current Block                                                                       
honeycomb_1  | State Check:  QmcHMPrRvv3ux4F2zQ8E4GF6Bxn6NyKREidccd2jtsaze7                        
honeycomb_1  | Account: disregardfiat                                                              
honeycomb_1  | Key: 5JP...                                                                         
honeycomb_1  | check supply check:state:110883621 vs check: 110883621: 0                           
honeycomb_1  | 62772802:Saved: QmXC598sPfjtpUbRBunNsAHmgcHQ7iRjfk5J9fLocsGiyF                      
honeycomb_1  | Requesting Blocks from: https://rpc.ecency.com/                                     
honeycomb_1  | 62772802                                                                            
honeycomb_1  | /honeycomb/node_modules/base-x/src/index.js:111                                     
honeycomb_1  |     throw new Error('Non-base' + BASE + ' character')                               
honeycomb_1  |     ^                                                                               
honeycomb_1  |                                                                                     
honeycomb_1  | Error: Non-base58 character                                                         
honeycomb_1  |     at Object.decode (/honeycomb/node_modules/base-x/src/index.js:111:11)           
honeycomb_1  |     at Function.fromWif (/honeycomb/node_modules/@hiveio/hive-js/lib/auth/ecc/src/key_private.js:184:49)
honeycomb_1  |     at toPrivateObj (/honeycomb/node_modules/@hiveio/hive-js/lib/auth/ecc/src/signature.js:185:37)
honeycomb_1  |     at Function.signBufferSha256 (/honeycomb/node_modules/@hiveio/hive-js/lib/auth/ecc/src/signature.js:129:27)
honeycomb_1  |     at Function.signBuffer (/honeycomb/node_modules/@hiveio/hive-js/lib/auth/ecc/src/signature.js:116:30)
honeycomb_1  |     at Object.Auth.signTransaction (/honeycomb/node_modules/@hiveio/hive-js/lib/auth/index.js:119:23)
honeycomb_1  |     at /honeycomb/msa.js:93:49                                                      
honeycomb_1  |     at /honeycomb/pathwise.js:102:9                                                 
honeycomb_1  |     at /honeycomb/node_modules/stream-to-array/index.js:54:9
honeycomb_1  |     at processTicksAndRejections (internal/process/task_queues.js:77:11)
honeycomb-spkcc_honeycomb_1 exited with code 0
honeycomb_1  | Deploying:                                                                          
honeycomb_1  | IPFS: DockerIPFS:5001            
honeycomb_1  | Using APIURL:  https://rpc.ecency.com/
honeycomb_1  | Streaming using mode irreversible
honeycomb_1  | Starting URL:  https://rpc.ecency.co

**Comment by disregardfiat** [comment]
I believe this has to do with keys entered into the .env or config.

**Comment by disregardfiat** [comment]
Check for spaces in .env with our keys
